# Generated by Django 5.1.7 on 2025-03-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='appUpload_e_first_n_f49d45_idx'), models.Index(fields=['email'], name='appUpload_e_email_3dda2f_idx'), models.Index(fields=['phone_number'], name='appUpload_e_phone_n_1aa5f3_idx'), models.Index(fields=['department'], name='appUpload_e_departm_0439a6_idx'), models.Index(fields=['salary'], name='appUpload_e_salary_efc547_idx'), models.Index(fields=['hire_date'], name='appUpload_e_hire_da_e68bc7_idx'), models.Index(fields=['created_at'], name='appUpload_e_created_7e4875_idx'), models.Index(fields=['updated_at'], name='appUpload_e_updated_57e1bd_idx'), models.Index(fields=['is_active'], name='appUpload_e_is_acti_0d643e_idx')],
            },
        ),
    ]
